config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home_page#show'
  resources :transactions, only: %i[index] do
    collection do
      match 'search', to: 'transactions#search', via: %i[get post], as: :search
    end
  end
  resources :categories do
    get 'add_money', on: :member, to: 'category_transactions#new'
    post 'update_balance', on: :member, to: 'category_transactions#create'
  end
  resources :balance_transactions, except: %i[index show]
  resources :cross_categories_transactions, only: %i[new create]
end

app/controllers/cross_categories_transactions_controller.rb
class CrossCategoriesTransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :create_new_form, only: %i[new create]

  def new
    @categories = current_user.categories
  end

  def create
    respond_to do |format|
      notice = if @form.validate(transaction_params) &&
                  CrossCategoriesTransactions::Creator.new(create_params).call
        t('.success')
      else
        t('.failure')
      end
      format.html { redirect_to categories_path, notice: notice }
      format.js { render layout: false }
    end
  end

  private

  def create_params
    {
      user_id: current_user.id,
      category_from_id: cross_categories_transactions_params[:category_from_id],
      category_to_id: cross_categories_transactions_params[:category_to_id],
      amount: transaction_params[:amount].to_f
    }
  end

  def cross_categories_transactions_params
    transaction_params[:cross_categories_transactions_attributes]
  end

  def create_new_form
    @form = CrossCategoriesTransactionForm.new(
      current_user.transactions.new,
      cross_categories_transactions: CrossCategoriesTransaction.new
    )
  end

  def transaction_params
    params.require(:transaction).permit(
      :amount,
      cross_categories_transactions_attributes: %i[category_from_id category_to_id]
    )
  end
end

app/views/cross_categories_transactions/_form.html.slim
= simple_form_for @form, url: cross_categories_transactions_path, method: :post do |f|
  = f.simple_fields_for :cross_categories_transactions do |t|
    = t.input :category_from_id, collection: @categories, prompt: t('select_category')
    = t.input :category_to_id, collection: @categories, prompt: t('select_category')
  = f.input :amount
  div.text-center
    = f.button :submit, t('.send'), class: 'btn btn-success'

app/views/cross_categories_transactions/new.html.slim
h2
  = t('.add_cross_categories_transaction')

= render 'cross_categories_transactions/form'

app/views/cross_categories_transactions/new.js.slim
| $("#modal-window .modal-content .modal-body").html("#{escape_javascript(render 'cross_categories_transactions/form')}");
| $("#modal-window .modal-content .modal-title").text("#{escape_javascript(t('.add_cross_categories_transaction'))}");
| $("#modal-window").modal('show');