config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home_page#show'
  resources :transactions, only: %i[index] do
    collection do
      match 'search', to: 'transactions#search', via: %i[get post], as: :search
    end
  end
  resources :categories do
    get 'add_money', on: :member, to: 'category_transactions#new'
    post 'update_balance', on: :member, to: 'category_transactions#create'
  end
  resources :balance_transactions, except: %i[index show]
  resources :cross_categories_transactions, only: %i[new create]
end

app/views/shared/_modal.html.slim
div id="modal-window" class="modal modal-#{style} hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5#exampleModalLabel.modal-title
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body

app/views/shared/_navbar.html.slim
nav.navbar.navbar-toggleable-md.navbar-inverse.bg-primary
  .container
    button.navbar-toggler.navbar-toggler-right[type="button" data-toggle="collapse" data-target="#navbar-responsive-button" aria-controls="navbar-responsive-button" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    a.navbar-brand[href="/"]= t('.brand_name')
    #navbar-responsive-button.collapse.navbar-collapse
    .nav.navbar-nav.navbar-right
      = link_to t('.activity'), transactions_path, class: 'nav-link mr-4'
      = link_to t('.categories'), categories_path, class: 'nav-link mr-4'
      - if current_user
        = render partial: 'transactions/balance'
      = render partial: 'shared/user_session'

app/views/shared/_user_session.html.slim
ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    li
      = link_to current_user.email, edit_user_registration_path, class: 'nav-link'
    li
      = link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'nav-link'
  - else
    li
      = link_to t('.login'), new_user_session_path, class: 'nav-link'
    li
      = link_to t('.register'), new_user_registration_path, class: 'nav-link'