config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home_page#show'
  resources :transactions, only: %i[index] do
    collection do
      match 'search', to: 'transactions#search', via: %i[get post], as: :search
    end
  end
  resources :categories do
    get 'add_money', on: :member, to: 'category_transactions#new'
    post 'update_balance', on: :member, to: 'category_transactions#create'
  end
  resources :balance_transactions, except: %i[index show]
  resources :cross_categories_transactions, only: %i[new create]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_transactions, dependent: :destroy
  has_many :categories_from, class_name: 'CrossCategoriesTransaction',
                             foreign_key: 'category_from',
                             dependent: :destroy
  has_many :categories_to, class_name: 'CrossCategoriesTransaction',
                           foreign_key: 'category_to',
                           dependent: :destroy
  belongs_to :categorizable, polymorphic: true, optional: true
  has_many :sub_categories, as: :categorizable, dependent: :destroy, class_name: 'Category'

  scope :top_category, -> { where(categorizable_type: 'User').order(created_at: :asc) }

  validates :amount, :name, presence: true
  validates :amount, numericality: {greater_than_or_equal_to: 0}
  validates :name, length: {minimum: 2, maximum: 40}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_category, only: %i[update destroy edit show]
  before_action :set_parent, only: %i[new create]

  def index
    @categories = current_user.categories.top_category
      .paginate(page: params[:page], per_page: 10).decorate
  end

  def show
    @transactions = category_history
    @subcategories = @category.sub_categories.decorate
  end

  def new
    @category = @parent.sub_categories.new
  end

  def create
    @category = Categories::Creator.new(parent: @parent, params: create_params).call
    respond_to do |format|
      if @category.persisted?
        flash[:notice] = t('.category_created')
      else
        flash[:alert] = t('.category_not_created')
      end
      format.html { redirect_to categories_path }
      format.js
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        flash[:notice] = t('.category_updated')
      else
        flash[:alert] = t('.category_not_updated')
      end
      format.html { redirect_to categories_path }
      format.js
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      flash[:notice] = t('.deleted_category_success')
      format.html { redirect_to categories_path }
      format.js
    end
  end

  def category_history
    @history = Categories::Historier.new(@category).result.flatten
    @transactions = Transaction.where(id: @history.map(&:id)).decorate
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def set_parent
    @parent ||= category || current_user
  end

  def category
    category_id = params[:category_id]
    current_user.categories.find_by(id: category_id) if category_id
  end

  def create_params
    category_params.merge(user_id: current_user.id)
  end

  def category_params
    params.require(:category).permit(
      :name,
      :amount
    )
  end
end

app/views/categories/_categories.html.slim
h4.text-center= t('.categories')
- @categories.each do |category|
  div.card.m-2.p-2
    h5.card-title.d-flex
      = link_to category.name, category_path(category), class: "text-center"
      span.badge.badge-primary.badge-pill.ml-auto
        = category.full_amount
    div.card-body.d-flex.justify-content-center
      = link_to t('.add_money'), add_money_category_path(category), {remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: 'btn btn-info' }

app/views/categories/_category.html.slim
div.card.m-2.p-2
  h5.card-title.d-flex.px-5
    = link_to category.name, category_path(category), class: "text-center"
    span.badge.badge-primary.badge-pill.ml-auto
      = category.full_amount
  div.card-body.mt-3
    = link_to t('.add_money'), add_money_category_path(category), {remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: 'btn btn-info mx-3' }
    = link_to t('.edit'), edit_category_path(category), { remote: true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: 'btn btn-info mx-3' }
    = link_to t('.delete'), category_path(category), method: :delete, data: { confirm: t('.are_you_sure') }, class: 'btn btn-danger delete-item mx-3'

app/views/categories/_form.html.slim
= simple_form_for @category do |f|
  = f.input :name
  = hidden_field_tag(:category_id, params[:category_id])
  div.text-center
    = f.button :submit, t('.add_category'), class: 'btn btn-success'

app/views/categories/category_history.html.slim
.col-md-12
  h4.text-center= @category.name
.col-md-12
  - unless @transactions.blank?
    table.table.table-striped.table-hover
      thead
        tr
          th[scope="col"]= t('.date')
          th= t('.amount')
          th= t('.comment')
      tbody
        - @transactions.each do |record|
          tr
            td= record.date
            td= record.amount
            td= record.comment
  - else
    h4= t('.no_transactions')

app/views/categories/edit.html.slim
=render 'categories/form'

app/views/categories/edit.js.slim
| $("#modal-window .modal-content .modal-body").html("#{{ j render 'categories/form'}}");
| $("#modal-window .modal-title").text("#{escape_javascript(t('.edit_category'))}");
| $("#modal-window").modal('show');

app/views/categories/index.html.slim
.row
  .col-md-7
    h3.header.text-center= t('.all_categories')
  .col-md-5.d-flex
    = link_to t('.new_category'), new_category_path, { remote: true, 'data-toggle': 'modal', 'data-target': '#modal-window', class: 'btn btn-info pull-right' }
    = link_to t('.add_cross_categories_transaction'), new_cross_categories_transaction_path, {remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: 'btn btn-primary ml-2'}
hr.my-4
.row
  div.d-flex.justify-content-around.align-content-center.flex-wrap
    = render partial: @categories
= render partial: 'shared/modal', locals: { style: 'primary' }

app/views/categories/new.html.slim
=render 'categories/form'

app/views/categories/new.js.slim
| $("#modal-window .modal-content .modal-body").html("#{escape_javascript(render 'categories/form')}");
| $("#modal-window .modal-title").text("#{escape_javascript(t('.new_category'))}");
| $("#modal-window").modal('show');

app/views/categories/show.html.slim
.row
  .col-md-9.col-xs-12
    h4.text-center= @category.name
    - unless @transactions.blank?
      table.table.table-striped.table-hover
        thead
          tr
            th[scope="col"]= t('.date')
            th= t('.amount')
            th= t('.comment')
        tbody
          - @transactions.each do |record|
            tr
              td= record.date
              td= record.amount
              td= record.comment
    - else
      h4= t('.no_transactions')
  .col-md-3.col-xs-12
    = link_to t('.add_sub_category'), new_category_path(category_id: @category.id),  {remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: 'btn btn-primary mb-3 ml-4'}
    - unless @subcategories.blank?
      h4.text-center
        = t('.subcategories')
      - @subcategories.each do |category|
        div.card.m-2.p-2
          h5.card-title.d-flex
            = link_to category.name, category_path(category), class: "text-center"
            span.badge.badge-primary.badge-pill.ml-auto
              = category.full_amount
          div.card-body.d-flex.justify-content-around.flex-wrap
              = link_to t('.add_money'), add_money_category_path(category), {remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: 'btn btn-info my-1' }
              = link_to t('.edit'), edit_category_path(category), { remote: true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: 'btn btn-info mx-3' }
              = link_to t('.delete'), category_path(category), method: :delete, data: { confirm: t('.are_you_sure') }, class: 'btn btn-danger delete-item mx-3'
= render partial: 'shared/modal', locals: { style: 'primary' }