config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home_page#show'
  resources :transactions, only: %i[index] do
    collection do
      match 'search', to: 'transactions#search', via: %i[get post], as: :search
    end
  end
  resources :categories do
    get 'add_money', on: :member, to: 'category_transactions#new'
    post 'update_balance', on: :member, to: 'category_transactions#create'
  end
  resources :balance_transactions, except: %i[index show]
  resources :cross_categories_transactions, only: %i[new create]
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :perform_search, only: %i[index search]

  def index
  end

  def search
    render :index
  end

  private

  def perform_search
    @search = current_user.transactions.includes(:transactinable).ransack(params[:q])
    @transactions = @search.result(distinct: true).order(created_at: :desc)
      .paginate(page: params[:page], per_page: 10).decorate
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :date)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def category_options
    options_for_select(categories_by_name_and_id)
  end

  private

  def categories_by_name_and_id
    current_user.categories.map { |category| [category.name, category.id] }
  end
end

app/views/transactions/_balance.html.slim
div.d-flex
  span.nav.navbar-text.mr-1= t('.balance')
  span.nav.navbar-text.mr-4= number_to_currency(current_user.balance)
  span.nav.navbar-text.mr-1= t('.free_balance')
  span.nav.navbar-text.mr-4= number_to_currency(current_user.free_balance)

app/views/transactions/_recent_transactions.html.slim
.col-md-10.offset-md-1
  - if @recent_records.blank?
    h4= t('.no_transactions')
  - else
    table.table.table-striped.table-hover
      thead
        tr
          th[scope="col"]= t('.date')
          th= t('.amount')
          th= t('.comment')
      tbody
      - @recent_records.each do |record|
        tr
          td.[scope="row"]= record.date
          td= record.amount
          td= record.comment

app/views/transactions/_search.html.slim
= search_form_for @search, url: search_transactions_path, method: :post, class: 'w-100' do |f|
  .card.my-2
    .card-header.pt-3
      .row
        .col-md-12
          h6
            = t('.filter_by_category')
    .card-body.d-flex.flex-row.justify-content-around.align-items-center.py-2
      div
        h6
          = t('.select_date_range')
        div.d-flex.flex-column
          = f.date_field :transactinable_of_BalanceTransaction_type_date_gt
          = f.date_field :transactinable_of_BalanceTransaction_type_date_lt
      div.d-flex.flex-column
        div
          h6
            = t('.for_transaction_to_category')
          = f.select :transactinable_of_CategoryTransaction_type_category_id_in,
            category_options, include_blank: true
        div.mt-2
          h6
            = t('.for_transactions_between_categories')
          .row
            .col
              = f.select :transactinable_of_CrossCategoriesTransaction_type_category_from_id_in,
                category_options, include_blank: true
            .col
              = f.select :transactinable_of_CrossCategoriesTransaction_type_category_to_id_in,
                category_options, include_blank: true
      = f.button :submit, class: "btn btn-primary" do
        = t('.submit')

app/views/transactions/_transactions.html.slim
.col-md-12
  - if !@transactions.blank?
    table.table.table-striped.table-hover
      thead
        tr
          th[scope="col"]= t('.date')
          th= t('.amount')
          th= t('.comment')
          th.text-center= t('.actions')
      tbody
        - @transactions.each do |record|
          tr
            td= record.date
            td= record.amount
            td= record.comment
            td.d-flex.justify-content-end
              - if record.balance_transaction?
                = link_to t('.edit_button'), edit_balance_transaction_path(record.transactinable.id), { remote: true, 'data-toggle': 'modal', 'data-target': '#modal-window', class: 'btn btn-info mx-3' }
                = link_to t('.delete_button'), balance_transaction_path(record), method: :delete, data: { confirm: t('.are_you_sure') }, class: 'btn btn-danger delete-item mx-3'
  - else
    h4= t('.no_transactions')

app/views/transactions/edit.html.slim
h3.text-center= t('.header')
.col-md-6.offset-md-3
  =render partial: 'transactions/form'

app/views/transactions/edit.js.slim
| $("#modal-window .modal-content .modal-body").html("#{{ j render 'transactions/form'}}");
| $("#modal-window .modal-title").text("#{escape_javascript(t('.edit_transaction'))}");
| $("#modal-window").modal('show');

app/views/transactions/index.html.slim
.row
  .col-md-10
    h6
      = render partial: 'balance' if current_user
.row
  .col-md-10
    h3.header.text-center= t('.activity_header')
  .col-md-2
    = link_to t('.new_transaction_button'), new_balance_transaction_path, { remote: true, 'data-toggle': "modal", 'data-target': '#modal-window', class: 'btn btn-info pull-right' }
.row
  = render 'transactions/search'

hr.my-4

.row
  = render 'transactions'

= will_paginate(@transactions)

= render partial: 'shared/modal', locals: { style: 'primary' }

app/views/transactions/new.html.slim
h3.text-center= t('.header')
.col-md-6.offset-md-3
  =render partial: 'transactions/form'

app/views/transactions/new.js.slim
| $("#modal-window .modal-content .modal-body").html("#{escape_javascript(render 'transactions/form')}");
| $("#modal-window .modal-title").text("#{escape_javascript(t('.new_transaction'))}");
| $("#modal-window").modal('show');